### ISSUE TITLE
以一种访问权限不允许的方式做了一个访问套接字的尝试

### ISSUE THREAD

**Issue by bling-yshs** [zpp0196/localsend-rs#9]
`cargo install --git https://github.com/zpp0196/localsend-rs.git`
然后
`localsend send "text to sent"`
就提示这个了。
是不是我操作的方式不太对...?
![image](https://github.com/zpp0196/localsend-rs/assets/41812674/b6a6e987-ba9f-4360-a534-1cbf7b112641)

**Comment by zpp0196** [comment]
试试这个 https://github.com/localsend/localsend/issues/125

**Comment by bling-yshs** [comment]
> 试试这个 [localsend/localsend#125](https://github.com/localsend/localsend/issues/125)

ok完美
